name: Extracting Features

on: push

jobs:
  linux_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Install dependencies
      run: |
        sudo apt-get install libsndfile1
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Install package
      run: |
        python setup.py install
    - name: Run tests/test_dataloader.py
      run: |
        echo "$PWD"
        ls $PWD
        python tests/test_dataloader.py "$PWD/tests/config.yml" "$PWD/tests/samples/labels.csv"

  macos_job:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Install package
        run: |
          python setup.py install
      - name: Run tests/test_dataloader.py
        run: |
          echo "$PWD"
          ls $PWD
          python tests/test_dataloader.py "$PWD/tests/config.yml" "$PWD/tests/samples/labels.csv"
